<?php

namespace App\Support\Payments;

use App\Enums\DeliveryMode;
use App\Models\Booking;
use App\Models\Payment;
use App\Models\TutorRequest;
use App\Support\SessionScheduler;
use Illuminate\Support\Facades\DB;

/**
 * Turns a successful payment into the things it pays for.
 *
 * Marking a payment successful is not the same as completing the transaction.
 * A payment that settles without this leaves no booking, no sessions and
 * nothing a payout can ever reach — the money is collected and stranded. Every
 * route to a successful payment therefore ends here: the gateway webhook, the
 * payer's return, manual mode, and an admin marking a payment paid by hand.
 *
 * Safe to call more than once. Gateways retry their webhooks and admins retry
 * their clicks, and neither may produce a second booking.
 */
class PaymentCompletion
{
    public function __construct(private readonly SessionScheduler $scheduler) {}

    /**
     * Complete the transaction behind a payment.
     *
     * @return bool whether this call was the one that completed it
     */
    public function complete(Payment $payment): bool
    {
        return DB::transaction(function () use ($payment) {
            // Re-read under lock: two webhook retries can arrive together.
            $payment = Payment::whereKey($payment->getKey())->lockForUpdate()->first();

            if (! $payment || $payment->status !== 'success') {
                return false;
            }

            if ($this->alreadyCompleted($payment)) {
                return false;
            }

            $enrolment = $payment->enrolment;

            if ($enrolment) {
                // A class seat already has its booking, created when the
                // student enrolled; paying only confirms it.
                $enrolment->update(['status' => 'active']);

                return true;
            }

            $this->createBookingsFor($payment);

            return true;
        });
    }

    /** Whether the work this payment pays for has already been done. */
    private function alreadyCompleted(Payment $payment): bool
    {
        if ($payment->enrolment) {
            return $payment->enrolment->status === 'active';
        }

        return $payment->booking_id !== null;
    }

    private function createBookingsFor(Payment $payment): void
    {
        if ($payment->booking_id) {
            return;
        }

        $tutorRequest = $payment->tutorRequest;
        if (! $tutorRequest) {
            return;
        }

        // Get all requests to create bookings for (grouped or single)
        $requests = $tutorRequest->request_group
            ? TutorRequest::where('request_group', $tutorRequest->request_group)
                ->where('status', 'matched')
                ->with(['matchedTutor.tutorProfile', 'package'])
                ->get()
            : collect([$tutorRequest->load(['matchedTutor.tutorProfile', 'package'])]);

        $firstBooking = null;

        foreach ($requests as $req) {
            $tutor = $req->matchedTutor;
            if (! $tutor) {
                continue;
            }

            $tutorProfile = $tutor->tutorProfile;
            $package = $req->package;

            $booking = Booking::create([
                'tutor_request_id' => $req->id,
                'tutor_id' => $tutor->id,
                'parent_id' => $req->parent_id,
                'student_id' => $req->student_id,
                'subject_id' => $req->subject_id,
                'schedule_day' => $req->schedule_day,
                'schedule_time' => $req->schedule_time,
                'duration_hours' => $req->duration_hours ?? $package?->duration_hours ?? 1,
                // bookings.location_type is NOT NULL but the request's is not:
                // it is only filled when a tutor accepts through the job flow,
                // so an admin-matched request would take the parent's money and
                // then fail to create anything. Derived from the delivery mode
                // when the request never said.
                'location_type' => $req->location_type ?? $this->locationTypeFor($req),
                'location_address' => $req->location_address,
                'hourly_rate' => $tutorProfile?->hourly_rate ?? 0,
                'commission_rate' => $tutorProfile?->commission_rate ?? Setting::defaultCommissionRate(),
                'status' => 'confirmed',
            ]);

            if (! $firstBooking) {
                $firstBooking = $booking;
            }

            // Sessions are what delivery is recorded against, so a booking
            // without them can never accrue under a per-session package. They
            // are laid out now rather than left to be generated by hand.
            $this->scheduler->ensure(
                $booking,
                max(1, (int) ($package?->total_sessions ?? 1)),
                durationHours: (float) $booking->duration_hours,
            );

            $req->update(['status' => 'closed']);
        }

        if ($firstBooking) {
            $payment->update(['booking_id' => $firstBooking->id]);

            // A grouped request spans several tutors under one payment; each
            // tutor is paid from their own booking, so split the recorded
            // totals across them now that the bookings exist.
            $payment->allocateToBookings();
        }
    }

    /**
     * The legacy location_type a delivery mode corresponds to.
     */
    private function locationTypeFor(TutorRequest $request): string
    {
        $mode = $request->deliveryMode();

        return match (true) {
            $mode->isOnline() => 'online',
            $mode === DeliveryMode::CentreGroup => 'center',
            default => 'home',
        };
    }
}
